### ISSUE TITLE
Split absent to attribute_absent and argument_absent.

### ISSUE THREAD

**Issue by jechol** [ash-project/ash#1015]
**Is your feature request related to a problem? Please describe.**
```elixir
validations do
  validate attribute_equals(:s_date, nil)
  validate absent(:s_date)
end
```

The above two have different behaviors:

* `attribute_equals`: It only looks at the attribute.
* `absent`: It first looks at the argument given in the changeset, and then it looks at the attribute.

In most cases, `attribute_equals` is the expected behavior. `absent` has an unexpected meaning that can be confusing.

**Describe the solution you'd like**
Split absent to attribute_absent and argument_absent.

**Express the feature either with a change to resource syntax, or with a change to the resource interface**

```elixir
validations do
  validate attribute_absent(:s_date)
  validate argument_absent(:s_date)
end
```

**Comment by zachdaniel** [comment]
🤔 I can see how this might be confusing. I'm not sure what the best way is to eliminate the confusion, primarily because some folks intentionally leverage this behavior to do arguments.

We could potentially support some syntax like `validate absent({:attribute, :s_date})`, but that doesn't solve for the potential confusion if you have an argument w/ the same name as an attribute. The reason why splitting them up won't be a solve-all is because you can mix and match arguments and attributes `validate present([:arg1, :arg2, :attr3], at_least: 1)`.

**Comment by jechol** [comment]
In that case, wouldn't it work to create three versions of every validation function?

non-prefix version: checks both argument and attribute (ex. present, equals)
argument version: checks only the argument (ex. argument_present, argument_equals)
attribute version: checks only the attribute (ex. attribute_present, attribute_equals)
Doing it this way would make the purpose clear from the function name, which seems like it would reduce the potential for confusion.

**Comment by zachdaniel** [comment]
Hmmmmmmm...perhaps just having an attributes present one would be enough. The current one applies to arguments or attributes, and attributes applies only to attributes. I'd accept that PR. It should be implemented by passing an additional option into the current validation.
