### ISSUE TITLE
bulk_create `status :partial_success` not set when not returning records

### ISSUE THREAD

**Issue by maennchen** [ash-project/ash#1332]
**Describe the bug**

When using `Ash.bulk_create/4`, the `status` field value of `Ash.BulkResult` depends on passing `return_records?: true`. If it is not set and the bulk creates more than one error, the status is set to `error`.

**To Reproduce**

```elixir
records = [
  %{field: :valid},
  %{field: :invalid}
]

Ash.bulk_create(Resource, :upsert).status
# => :error

Ash.bulk_create(Resource, :upsert, return_records?: true).status
# => :partial_success
```

**Expected behavior**

I would expect the status field to have the following value:

* `:success` - `error_count == 0`
* `:error` - `error_count == record_count`
* `:partial_success` - `error_count in 1..(record_count - 1)`

The option `return_records?` should not have any effect on the `status`.

**Runtime**
 - Elixir version: `1.17.2`
 - Erlang version: `27.0.1`
 - OS: `Ubuntu 22.04.4 LTS (Jammy Jellyfish)`
 - Ash version: `3.2.5`
 - any related extension versions:
 ```
* ash_admin 0.11.3 (Hex package) (mix)
  locked at 0.11.3 (ash_admin) ae700d8f
* ash_graphql 1.2.1 (Hex package) (mix)
  locked at 1.2.1 (ash_graphql) 44a9a11f
* ash_phoenix 2.0.4 (Hex package) (mix)
  locked at 2.0.4 (ash_phoenix) f3ea5309
* ash_postgres 2.1.12 (Hex package) (mix)
  locked at 2.1.12 (ash_postgres) 47aaf473
* ash_sql 0.2.25 (Hex package) (mix)
  locked at 0.2.25 (ash_sql) caeb8c5e
```

**Additional context**

* Real Life batch contained 100 entries, not 2
* Upsert with `upsert_identity` provided

**Comment by zachdaniel** [comment]
Thanks for the report, I will address today or tomorrow 🙇

**Comment by zachdaniel** [comment]
Alright, so I'm addressing this now. It unfortunately can't quite be boiled down to

```
:success - error_count == 0
:error - error_count == record_count
:partial_success - error_count in 1..(record_count - 1)
```
specifically because there is no restriction that there is only one error per insert. The main bug here is actually a simple one, which is that the result should not have had `records: []` when `return_records?: false`, but rather `records: nil`, and we were using that empty list to express that there were no successes.

I'm doing two things:

1. fixing that bug, ensuring `nil` is returned.
2. storing whether any of our calls were successful, to allow for determining `:error` instead of `:partial_success` in cases where all batches failed (a new bug arising while fixing yours).

**Comment by maennchen** [comment]
@zachdaniel Sounds great, testing it now.

**Comment by zachdaniel** [comment]
I sometimes rely on the "test subprojects" test suite to find issues (in this case specifically from `ash_postgres` in this case), so just fair warning that I haven't verified it against all packages yet :)

**Comment by maennchen** [comment]
@zachdaniel I've found the problem in a test that uses the code interface. I don't have any APIs for it yet.

I can confirm that it works as intended. Thanks for fixing it :)
