### ISSUE TITLE
Consider `:infer` option for DSL simplification

### ISSUE THREAD

**Issue by sitch** [ash-project/ash#136]
Firstly just wanted to say great job so far! :1st_place_medal: I'm loving this project! :heart: : 

I think there's some configuration that could be easily remedied by having inference over DSLs.

## Consider

From the `ash_example` repo this json api definition:
```elixir
json_api do
  type "user"

  routes do
    base "/users"

    get :me, route: "/me"
    index :read
    post :create
    patch :update
    delete :destroy
  end

  fields [:first_name, :last_name, :representative, :admin]
end
```

## Identifying inferable duplications

The `.type/1`, `.fields/1`, and `.routes/1` all contain what would be considered default, inferable values from the lens of a Phoenix controller.

```elixir
json_api do
  #=========================================
  # Inferable via `__CALLER__ |> singular()`
  #=========================================
  # type "user"

  routes do
    #=========================================
    # Inferable via `__CALLER__ |> plural()` 
    #=========================================
    # base "/users"

    #=========================================
    # *Non-inferable*
    #=========================================
    get :me, route: "/me"

    #=========================================
    # Inferable via `__CALLER__ |> actions()`
    #=========================================
    # index :read
    # post :create
    # patch :update
    # delete :destroy
  end

  #=========================================
  # Inferable via `__CALLER__ |> struct_fields()`
  #=========================================
  # fields [:first_name, :last_name, :representative, :admin]
end
```

## Suggested Syntax

So you could have:

### Minimalist
Simplest possible definition
```elixir
json_api :infer 
```

### With definition addition
Add to the default `:infer` options
```elixir
json_api :infer do
  routes :infer do
    get :me, route: "/me"
  end
end
```
### With definition overrides
Override to the default `:infer` options

```elixir
json_api :infer do
  fields [:first_name, :last_name]
  routes :infer, except: [:delete]
end
```

### Resources so dry they spittin' cotton

```elixir
defmodule ExampleResource do
  use Ash.Resource

  pubsub :infer
  postgres :infer
  graphql :infer 
  json_api :infer 
  actions :infer
  policies :infer

  attributes do
    ...
  end
```

## Conclusion

The most common / expected configuration can be inferred from application configs like `:default_repo`, `:default_endpoint`, or `:default_resource_policies` in addition to the resource `attributes` and `actions`.

## Drawbacks

This could lead into too much "magic" territory, but I think for the most part this is really just removing duplicate tokens which would otherwise reduce the malleability of the code.

This can also open up things like inference extensions that can do reflection on the database to infer assocs automatically.

**Comment by zachdaniel** [comment]
@sitch I really like where you're going with this. We're chatting about some similar(but ultimately separate) concepts over in #33. I like the idea of having a standard way of expressing that you want the "default" version of something, especially because that could actually be generalized via the extension builder. I wrote the generic extension builder specifically to support more advanced concepts being supported "globally", from custom extensions to extensions provided by core. For example, this is the definition for the `routes` section in json_api:

```elixir
  @routes %Ash.Dsl.Section{
    name: :routes,
    describe: "Configure the routes that will be exposed via the JSON:API",
    schema: [
      base: [
        type: :string,
        required: true,
        doc: "The base route for the resource, e.g `\"/users\"`"
      ]
    ],
    entities: [
      @get,
      @index,
      @post,
      @patch,
      @delete,
      @related,
      @relationship,
      @post_to_relationship,
      @patch_relationship,
      @delete_from_relationship
    ]
  }
```
```elixir
  @routes %Ash.Dsl.Section{
    ...,
    infer: AshJsonApi.Resource.Transformers.InferRoutes
  }
```
Then, if the `routes :infer` option was selected, that transformer would be run for that resource. The "difficult" thing here is that the macro syntax that actually backs the DSL is a bit finicky(probably something a refactor/rewrite could solve). The point is that I may not necessarily be able to support `section :infer`, and I might need to make it some kind of custom call, e.g:

```
defmodule ExampleResource do
  use Ash.Resource

  infer :pubsub
  infer :postgres
  infer :graphql
  infer :json_api
  infer :actions
  infer :policies

  attributes do
    ...
  end
end
```

Looking at it, that might actually be nice because we could then take arguments to the `infer` call, which could be provided the transformer (somehow). E.g
```
defmodule ExampleResource do
  use Ash.Resource

  infer :graphql, only: [:create_example_resource]
  infer :json_api, except_routes: [:delete]

  attributes do
    ...
  end
end
```

A nice thing is that you can actually use sections multiple times (might be some kinks to work out, but it should definitely be doable), so if you want to simply "override" the `delete` route, you could say:

```
defmodule ExampleResource do
  use Ash.Resource

  infer :json_api, except_routes: [:delete]

  json_api do
    routes do
      delete :destroy, route: "/clear"
    end
  end

  attributes do
    ...
  end
end
```

The only other question I have really is whether or not `infer` is the best term. I like it better than `default` because that is a loaded term w/ how attributes/other things work.

**Comment by zachdaniel** [comment]
Also: thanks for all the thought you put into this, I'm really glad you're enjoying the project so far.

**Comment by sitch** [comment]
I definitely agree that `infer` > `default` as default is super over-loaded as a programming term in general, and agree that there might be something better out there than `infer`.

I can take a look at the DSL builder as it shouldn't affect the arity, it would just either have to support improper lists or have it be `json_api infer: true, do: ...` to ease use / avoid overly relaxed typespec-ing

**Comment by zachdaniel** [comment]
A couple things:

Right now sections don't have any arguments, but it would be possible to do it that way. My only hesitation is if you want to provide options for how to do said inference. Like if we want an `except` option. That looks bad as an argument:

```
json_api infer: [except: [:foo, :bar]] do

end
```

Whereas something like

```
json_api do
  infer :routes, except: [...]
end
```

allows adding options.

Open to creative solutions/alternatives. Beware the DSL generation code, there be dragons :D

**Comment by zachdaniel** [comment]
This one definitely needs a lot of thought. I think it runs the risk of eliminating some of the explicitness that we're going for here, specifically, with one line of code being able to produce `5 + 5 * relationship_count` relationships. It might be better to introduce `infer` in such a way that you at least have to explicitly list the things you want. e.g

```
json_api do
  infer(:routes, [:get, :update, :destroy, :create])
  infer(:relationship_routes, [:posts, :likes, :profile])
end

postgres do
  infer([:table, :repo])
end
```

I don't think exactly what I posted is necessarily the answer, but the important take away here is that our heuristic for a successful DSL, when it comes to reading that DSL, is not character count, it is expressiveness.

I don't like the idea of someone wanting to know if there is a route to relate a comment to a post, and coming to the resource and seeing:
```
json_api :infer
```
And having to pull up the documentation for json_api because they don't recall if it automatically makes relationship routes. That kind of thing.

**Comment by zachdaniel** [comment]
Closing for now, as we are unlikely to add this kind of option, favoring more explicit approaches. Ways to eliminate duplication that retain explicitness are always welcome though.
