### ISSUE TITLE
The sorting order is opposite to what I intended.

### ISSUE THREAD

**Issue by jechol** [ash-project/ash#1382]
**Describe the bug**
The sorting order is opposite to what I intended.

**To Reproduce**
```elixir
defmodule Post do
  preparations do
    prepare build(sort: [:a])
  end

  actions do
    read :read do
      prepare build(sort: [:b])
    end
  end
end

defmodule User do
  relationships do
    has_many :posts do
      sort [:c]
    end
  end
end
```

In this case, when we do `user |> Ash.load(:posts)`, the sorting order becomes `[:a, :b, :c]`, but I think it should be `[:c, :b, :a]`. This is because the scope of application narrows from preparations applied to all actions, to the specific read action, and then to has_many which applies only to a specific relationship within that action. As the scope becomes narrower, it represents a more specific use case, so it seems it should have higher priority.

**Expected behavior**
The sorting order should be `[:c, :b, :a]`.

If changing the application order is difficult, it would be nice if there was a way to pass `prepend?: true` in `build(sort: [:b])`.

**Comment by zachdaniel** [comment]
I think the current behavior is preferred as the default, otherwise building something like a sortable table based off a relationship would be quite difficult. It's easy to change, but would be a breaking change and not the generally desired behavior IMO.

PRs welcome to add a `prepend_sort` key to `Ash.Query.build/2` which would then mean that key is available in `build/2`. With that said, I don't think it's what you need. The problem here isn't "scope" but "order". Global preparations are applied first, then action specific preparations, and then relationship modifiers.

You'll have to add conditions or modifications to your preparations.
