### ISSUE TITLE
How to set actor

### ISSUE THREAD

**Issue by michaelst** [ash-project/ash#218]
I see in the documentation that you can filter by actor 
```  
read :me do
    # An action that auto filters to only return the user for the current user
    filter [id: actor(:id)]
  end
```

However, I don't see any documentation about how to actually set the resource that is the actor.

**Comment by zachdaniel** [comment]
You can set it as an option to any of the calls in your `Api` module, as well as calls to `Ash.Changeset.for_(create|update|destroy)/4` and `Ash.Query.for_read/4`. If you set it in the changeset/query function, it will be retained for the call to the Api, so that if you are using the changeset/query functions, you should just set it there. For example:

``elixir
MyApp.User
# third argument is action input
|> Ash.Query.for_read!(:me, %{}, actor: current_user)
|> Api.read!()
```

However, your action takes no arguments, so you can just use the shorthand:

```elixir
Api.read!(MyApp.User, action: :me, actor: current_user)
```

If you define a code interface, e.g
```elixir
code_interface do
  define :get_me, action: :read, get?: true #<- get? says it should only return one record
end
```

You could then say:
```elixir
Api.get_me!(actor: current_user)
```

Hope that helps! Let me know if you run into any issues/have any more questions.

**Comment by michaelst** [comment]
I'm connecting this with ash_graphql so as far as I can tell the Api.read function call never happens explicity in my code, where do I put actor, is there a specific context key?

**Comment by zachdaniel** [comment]
Ah, yes. It goes in the `:actor` context key of the absinthe context.

**Comment by zachdaniel** [comment]
I'm *very* surprised that there isn't already a guide in ash_graphql about setting that up. If you are interested, you could PR a short example of it to a guide in the `documentation` folder of the project.

**Comment by zachdaniel** [comment]
If not, I'll add it :)

**Comment by zachdaniel** [comment]
Here is an example: 
https://github.com/ash-project/example_with_auth/blob/main/lib/example_with_auth_web/plugs/context.ex

**Comment by zachdaniel** [comment]
As a side-note, I think you'll run into issues putting that action into ash_graphql at the moment, because there isn't a way to turn off the required argument for `get` queries. For now you could just make a list query, or you could write a custom query and just call your api inside a resolver. If you make an issue on ash_graphql I'll get to it.
