### ISSUE TITLE
Always import latest version of Ash projects in getting started guides.

### ISSUE THREAD

**Issue by tlietz** [ash-project/ash#298]
I propose that we import the latest version of Ash projects in the getting started guides to create a more seamless onboarding experience.

These:
```elixir 
{:ash, "~> x.x.x"}
```

```elixir
{:ash_postgres, "~> 0.25.5"},
{:ash, "~> 1.24"}
```

Would be changed to:
```elixir
{:ash, ">= 0.0.0"}
```
```elixir
{:ash_postgres, ">= 0.0.0"},
{:ash, ">= 0.0.0"}
```

**Comment by zachdaniel** [comment]
Great idea! I'm working on a new documentation site, so what we can do is add special markdown format to the documentation, where if you say something like `<extension_version(extension)>` we can replace it with the latest version? All of the guides will be rewritten and moved to the new docs site, so that should work.

**Comment by zachdaniel** [comment]
This is a feature in new ash-hq guides.
