### ISSUE TITLE
Broken read-only relationships 

### ISSUE THREAD

**Issue by smt116** [ash-project/ash#346]
**Describe the bug**
It looks like the following change broke the read-only relationships: https://github.com/ash-project/ash/commit/ac4590a0cac155d9b999b66bbf048dd5f6371810. The documentation on the other hand says that the option is valid (see https://hexdocs.pm/ash/Ash.Resource.Dsl.html#module-has_many).

**Expected behavior**
Read-only relationships should be possible for making definitions like `has_one :latest_comment` or `has_many :funds_transfers_in_progress` possible.

**Runtime**
 - Ash version 1.52.0-rc.16

**Comment by zachdaniel** [comment]
The documentation still shows that option because what you linked to is the last major release, the RC docs are problematically not showing the DSL docs. So the main reason `writable?` was changed in that way was because by removing the `relationships` option from changeset casting, there is no implicit modification of relationships anywhere. Any modification of relationships would have to explicitly be done via `manage_relationship`, but this issue has caused me to reconsider and there is still the case for it to specify intent and to prevent someone using `manage_relationship` on the relationship in general. I'll put the option back shortly.

**Comment by zachdaniel** [comment]
Yeah, this was just a mistake on my part, not sure why I thought this would be reasonable to remove. Easily rectified :)

**Comment by zachdaniel** [comment]
Okay, this should now be resolved.

**Comment by zachdaniel** [comment]
What I *did* still remove is the `relationships` option when casting changesets, as it was a very indirect way to manage relationships that I think is very unlikely was being used.
