### ISSUE TITLE
Using get/2 with an identity is raising Ash.Error.Invalid instead of returning {:error, %Ash.Error.Query.NotFound{}}

### ISSUE THREAD

**Issue by tim-smart** [ash-project/ash#363]
**Runtime**
 - Elixir version: 1.13.4 OTP 25
 - OS: alpine
 - Ash version: 1.53.2

```elixir
resource |> Resources.Api.get(source: :youtube, source_id: "xxx")
```

![image](https://user-images.githubusercontent.com/40680/185830158-4f251055-cf2a-4e3e-970b-ca3941202892.png)

**Comment by tim-smart** [comment]
Original code using get/2:

```elixir
def find_or_create(
      %Ash.Changeset{
        resource: resource,
        attributes: %{
          source: source,
          source_id: source_id
        }
      } = changeset
    ) do
  with {:ok, record} <- get(resource, source: source, source_id: source_id) do
    {:ok, record}
  else
    {:error, %Ash.Error.Query.NotFound{}} -> create(changeset)
    err -> err
  end
end
```

**Comment by zachdaniel** [comment]
Ah, okay so I think what might be happening here is that we changed the errors for consistency. It doesn't return `%Ash.Error.Query.NotFound{}` anymore, it returns `%Ash.Error.Invalid{errors: [..., %Ash.Error.Query.NotFound{}]}`.

Somewhere else I think you are calling a function with a `!` and this error is being bubbled up, because your function is actually returning `{:error, %Ash.Error.Invalid{}}` and its getting raised further down the road.

```elixir
def find_or_create(
      %Ash.Changeset{
        resource: resource,
        attributes: %{
          source: source,
          source_id: source_id
        }
      } = changeset
    ) do
  with {:ok, record} <- get(resource, source: source, source_id: source_id) do
    {:ok, record}
  else
    # If there was exactly one error, and it is a `NotFound`
    {:error, %Ash.Error.Invalid{errors: [%Ash.Error.Query.NotFound{}}} -> 
      create(changeset)
    err -> err
  end
end
```

**Comment by zachdaniel** [comment]
I'll add something to the upgrading guide for others.

**Comment by tim-smart** [comment]
Yes matching against the Invalid struct is working, thanks!
