### ISSUE TITLE
Wrong return type for the read action

### ISSUE THREAD

**Issue by smt116** [ash-project/ash#368]
**Describe the bug**
The read action has an invalid return type spec when used with keyset pagination. See https://github.com/ash-project/ash/blob/v1.53.3/lib/ash/api/api.ex#L392-L395. The return type for such an action is `Ash.Page.Keyset.t()`.

I'm unsure if we should expand the read action's return type. What we could do is to have a separate action for the pagination (like `read_page` instead of `read`). Also, the `Ash.Page.Keyset.t()` should specify what kind of resources it contains.

**To Reproduce**
Create a function that uses keyset pagination and run a dialyzer on it.

**Expected behavior**
No warning from Dialyzer check.

**Runtime**
 - Ash version 1.53.3

**Comment by zachdaniel** [comment]
For now, the simple fix is to add `Ash.Page.page()` to the response from `read!`. We could add a `read_page` in the future for cases where you are sure that you're going to get a page back. There is a bigger effort involved in parameterizing all of the typespecs, but it would definitely be a great idea to do so :)

Fixed in bb4a3b34b3b790558e789ad3e79a1aa3e10e2fcc
