### ISSUE TITLE
Unanticpated arg() Behaviour

### ISSUE THREAD

**Issue by kingdomcoding** [ash-project/ash#425]
Calling `arg(:argument)` doesn't always behave as anticipated.
On certain occasions, a tuple is returned rather than the expected value.

Here are examples I've encountered:
- `validate one_of(:correct_options, arg(:options))` -- `arg(:options))` returns `{:_arg, :options}`
- `change set_attribute(:separator, %{value1: arg(:arg1), value2: arg(:arg2)})` -- `arg(:arg1)` and `arg(:arg2)` return `{:_arg, :arg1}` and `{:_arg, :arg2}` respectively.

So,
1. Why does it return a tuple rather than what was expected?
2. Can the behaviour be modified to function as expected?
3. Can `arg` be better documented?

**Comment by zimt28** [comment]
Hi @kingdomcoding!

Did your application compile? What you're trying to do isn't currently supported and shouldn't actually work.

* `one_of/2` expects a list as the second argument and will throw an error:
```
** (Spark.Error.DslError) [App.Your.Resource]
 actions -> validate:
  expected :values to be a list, got: {:_arg, :name}
```

* `set_attribute/2` allows passing an argument as the second argument _directly_ but doesn't walk nested structures, so this is expected behavior, too.

So:
1. `arg/1` is just a small helper ([`def arg(name), do: {:_arg, name}`](https://github.com/ash-project/ash/blob/8092cd899ad3dfe8ca0e681bc6400e9806ac641e/lib/ash/filter/template_helpers.ex#L13-L14)) which generates the tuple you're seeing. Some built-in validations and changes will replace it with an actual value but not in the cases you described above.
2. You can create custom [validations](https://ash-hq.org/docs/module/ash/latest/ash-resource-validation) and [changes](https://ash-hq.org/docs/module/ash/latest/ash-resource-change), I'd recommend looking at the [built-in validations](https://github.com/ash-project/ash/tree/main/lib/ash/resource/validation) and [built-in changes](https://github.com/ash-project/ash/tree/main/lib/ash/resource/change) as examples.
3. Yes, we're always working on docs and [ash-hq.org](https://ash-hq.org), currently it's not always easy to find what you're looking for :)

**Comment by zimt28** [comment]
I now think I should just have asked what you're actually trying to do 🥲 What does your `separator` attribute look like? Unless you're storing a map using the `:map` type you'll probably want to use `Ash.Changeset.manage_relationship/4`. You can find more information [here](https://ash-hq.org/docs/guides/ash/latest/topics/managing-relationships.md) and [here](https://ash-hq.org/docs/guides/ash/latest/topics/managing-relationships.md).

**Comment by zachdaniel** [comment]
Yeah, so `arg/1` does explicitly return `{:_arg, name}`, and its original purpose was to be used specifically in "expressions". An Ash expression, for example, might look like this:
```elixir
read :read do
  argument :foo, :string
  
  filter expr(name == ^arg(:foo))
end
```

However, for convenience, some other places may support that format, but its really just a matter of them supporting explicit uses of `{:_arg, arg}`. For example `set_attribute(:foo, arg(:foo))` is supported, because the code in `Ash.Resource.Change.SetAttribute` explicitly matches on it: https://github.com/ash-project/ash/blob/main/lib/ash/resource/change/set_attribute.ex#L25

I can see why this would be quite confusing, although I'm not sure what the best way to catch this at compile time would be without a lot of expensive traversals that would be quite brittle. The general idea is when you start wanting to do things like this:

```elixir
change set_attribute(:separator, %{value1: arg(:arg1), value2: arg(:arg2)})
```

that you would simply write your own change instead of using a builtin, for example:

```elixir
defmodule MyModule.SetSeparator do
  use Ash.Resource.Change
  
  def change(changeset, _, _) do
    arg1 = Ash.Changeset.get_argument(changeset, :arg1)
    ...
    
    Ash.Changeset.set_attribute(changeset, ....)
  end
end

...
change MyModule.SetSeparator
```

As for the built in validations, the atoms that you provide should generally be checked against attributes *or* arguments (they all use `Ash.Changeset.fetch_argument_or_change/2`).

So
```elixir
validate one_of(:correct_options, :options)
```
may be all you need there.

For validations as well, you can define custom ones:

```elixir
defmodule MyCustomValidation do
  use Ash.Resource.Validation
  
  def validate(changeset, _, _) do
     #return :ok | {:error, error}
  end
end

validate MyCustomValidation
```

**Comment by zachdaniel** [comment]
I'll leave this open to allow for discusson on how to prevent this kind of confusion, although there isn't really a bug here per-se.

**Comment by kingdomcoding** [comment]
Thank you for your really detailed response, @zimt28  and @zachdaniel 

I have followed @zachdaniel's suggestion to write my own validators. This has solved my problem and following the built-in validators has also helped me understand Ash's internal workings.

Yet, the examples I gave might seem intuitive to any newcomer to the library.

So, for the sake of dev-ex (and since declarative design is core to Ash), do you think we can support expressions similar to the examples I gave above?

PS: Can macros help us in any way?

**Comment by zachdaniel** [comment]
Its a really interesting question. Its *possible*, and in fact we do something like this for `Ash.Flow`, i.e you can say `input %{foo: %{bar: %{baz: arg(:arg)}}}` and it will traverse the expression. This is something we may be able to do...I'll think it over. As far as I know thats the only real way to support it.

**Comment by zachdaniel** [comment]
Given that the only place you'd expect to use this is in change/validation/policy opts, I think I can actually do this. What we'd do is put a step just before calling the relevant module where we could replace template values. This does mean that the `init/1` hook on these modules is now *fully* useless though, because the contents could be given by a dynamic expression and so the init can't really do any work ahead of time. I think I might deprecate the init hook anyway because we removed it from doing its work at compile due to compile time issues.

**Comment by zachdaniel** [comment]
We won't be able to do it at compile time unfortunately, since arg values aren't known then, so it will have to be done every time a given change is run. Maybe some day when we support anonymous functions in the DSL we could do something like checking at compile time if the expression has any args, and then replace it with a function that takes the args and returns the value. That could be done with relatively good performance implications I think. But generally arguments to changes/validations are things like `max: 1, min: 10`, so its not like traversing them on every invocation is going to be especially expensive.
