### ISSUE TITLE
Actor not available in module calculation context

### ISSUE THREAD

**Issue by ahey** [ash-project/ash#462]
**Describe the bug**
The actor is not currently available in the context of a module calculation.

**To Reproduce**
A [failing test has been created to reproduce this issue](https://github.com/ahey/ash/commit/3e7ed5aaae2dfb6c81906f696e619f2642a9e82b).

**Expected behavior**
It was expected that the actor would be available

**Runtime**
 - Elixir version: 1.14.2
 - Erlang version: 25.1.2
 - OS: MacOS 13.0
 - Ash version: 2.4.26

**Additional context**
This is in response to a discussion in discord about making the `can?` function available via GQL so that front-end clients can find out what they are allowed to do.

**Comment by zachdaniel** [comment]
This will be a bit of a project, but I think it can be done and likely should be done. What we would do here is:

- [ ] When running the read action, set three pieces of query context (although a bit duplicative, this simplifies part1 significantly), `actor`, `tenant`, and `authorize?`. It is duplicative because this information lives in the query already.
- [ ] Anywhere we call `.calculate` or `.expression` on a calculation module, we need to make sure to include in the context a `context` key which reflects the context of the query being run.

The challenge with part #2 there is that we need to ash_postgres, where we make a lot of calls to `.expression` in various places, and we need to make sure that the query context is available there. This is doable, but will take some plumbing/verification work. This would be a decent first contribution for anyone interested.

**Comment by zachdaniel** [comment]
In retrospect, this is a bit more challenging than it would seem. It would mean actor awareness in various different levels of the application where it shouldn't really be. However, the actor id and/or actor as a whole could be provided as an argument to the calculation, potentially? Still need to think on this.

**Comment by zachdaniel** [comment]
This is addressed in main

**Comment by ahey** [comment]
Thanks for adding this in @zachdaniel 😄
