### ISSUE TITLE
Custom ETS Support for data_layer.

### ISSUE THREAD

**Issue by Edward-Heales** [ash-project/ash#498]
I'm currently checking out Ash as a possibility for our new system, one problem I've found whilst completed the getting started documentation is that it recommends to not use the `Ash.DataLayer.Ets` for prod.
Maybe there is something I can use in the docs that I haven't read up to yet, but my current setup is using the Cachex package to store various things required for the system, im wondering would it be possible to specify a custom ETS like so:

```elixir
use Ash.Resource
  data_layer: Cachex.start_link(name: :ash_cache, limit: limit(size: 500, policy: Cachex.Policy.LRW, reclaim: 0.5)) 
```

I don't really want to be going to postgres every single time to check/update session information.

**Comment by zachdaniel** [comment]
Hey there! 
A few notes: You can use ETS in prod, but the main issue is one of "scalability" in terms of treating it as a general purpose data store. Because when you run a list query and filter, we do all of that filtering after the fact, none of it is turned into match statements that we issue when running queries. But that isn't necessarily an issue depending on your usage patterns/scale.

To do do something similar to what you posted, you'd need to write a custom data layer, which is a behaviour that you implement (`Ash.DataLayer`).

However, in many cases that is not necessary. What you can do instead is use a resource without a data layer, and implement the actions manually. For example, if I wanted to store some data in cachex I might do something like this:

```elixir
use Ash.Resource

actions do
  read :get_session do
    get? true
    
     argument :user_id, :uuid do
         allow_nil? false
     end
     
     manual fn query -> 
       user_id = Ash.Changeset.get_argument(query, :user_id)
       {:ok, [get_user_session(user_id)]}
     end
     
     # or define a module that implements `Ash.Resource.ManualRead`
     manual LookupSession
  end
end
```
