### ISSUE TITLE
Remove the need to add the `Ash.Policy.Authorizer` extension to resources

### ISSUE THREAD

**Issue by jimsynz** [ash-project/ash#768]
It seems like since this is in core we can probably just deprecate this extension and always turn on the features.

**Comment by zachdaniel** [comment]
Based on the current behavior, we can't really do this. The reason is that it would tangibly change behavior in certain cases. If you do this:

`Api.read!(Resource, authorize?: true)` and it has the policy authorizer but no policies, it fails to protect you from accidentally not adding policies to a resource that should have them. If we add it by default, it changes the behavior of adding `authorize?: true` to resources with no authorizers set. This is important because api extensions always set `authorize?: true`.
