### ISSUE TITLE
Add a way to return an error from a calculation 

### ISSUE THREAD

**Issue by rbino** [ash-project/ash#887]
As discussed [on the Elixir forum](https://elixirforum.com/t/handling-partial-failures-when-exposing-external-data-in-a-resource/61100), it would be nice to have a way to expose the failure of a calculation if it's fallible (e.g. if it queries an external API).

This way extensions that are able to do so (e.g. AshGraphql) can expose partial results alongside failures instead of just returning `nil` which doesn't convey the idea of a (possibly temporary) error.

**Comment by sevenseacat** [comment]
This needs to be done more generally - if a calculation is extracted to a separate module and something goes wrong while running the `calculate` function, the returned error is less than helpful. 

It surfaces as something like:

```
[error] GenServer #PID<0.13535.0> terminating
** (FunctionClauseError) no function clause matching in anonymous fn/2 in 
   Ash.Actions.Read.Relationships.attach_related_records/2
    (ash 2.21.15) lib/ash/actions/read/relationships.ex:28: anonymous fn({:__exception__, 
%FunctionClauseError{module: Ash.Actions.Read.Relationships, function: :"-
attach_related_records/2-fun-0-", arity: 2, kind: nil, args: nil, clauses: nil}, 
[{Ash.Actions.Read.Relationships, :"-attach_related_records/2-fun-0-", [{:__exception__, 
%FunctionClauseError{module: MyApp.Segment.CalculateColour, function: :"-calculate/3-fun-1-", 
arity: 1, kind: nil, args: nil, clauses: nil}, [{MyApp.Segment.CalculateColour, :"-calculate/3-
fun-1-", [nil], [file: ~c"lib/my_app/segment/calculations/calculate_colour.ex", line: 57]}, 
{Map, :get_and_update, 3, [file: ~c"lib/map.ex", line: 957]}, ...
```

Because the `calculate` function has not returned something enumerable that can be iterated over and attached to records. The actual error is tucked deep in there (eg. in this case, `calculate_colour.ex:57` but it's hard to find.

**Comment by zachdaniel** [comment]
I believe we've fixed that specific very ugly pattern match issue in `main`, so the error messaging should be a bit better. With that said, I think I'm actually going to close this issue. Ultimately what this issue is requesting is the ability to return "partial success and failure". This is doable with things like custom types, etc. You can have a return type that is a union of the result or a type representing an error.

I don't think we'll be adding anything in core (at least not anytime soon) to do this kind of thing automatically.
